# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-03 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yingyong1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gupiao',
        ),
    ]
