# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-05 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yingyong1', '0003_auto_20190103_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gupiao',
            name='kp',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='sp',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='zd',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='zg',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
