# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yingyong1', '0009_auto_20190216_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gupiao',
            name='cje',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='cjl',
            field=models.DecimalField(decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='kp',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='sp',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='today_boll_center_line',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='today_boll_down_line',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='today_boll_up_line',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='today_ma20',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='today_md',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='zd',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='zg',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
