# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yingyong1', '0010_auto_20190216_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gupiao',
            name='today_boll_center_line',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='today_boll_down_line',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='today_boll_up_line',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='today_ma20',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gupiao',
            name='today_md',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
