# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-20 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yingyong1', '0012_auto_20190219_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='gupiao',
            name='bls_1_1',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gupiao',
            name='blx_1_1',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gupiao',
            name='blz_1_1',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gupiao',
            name='today_ma20_1_1',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gupiao',
            name='today_md_1_1',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
