# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yingyong1', '0002_delete_gupiao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gupiao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('kp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('zg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('zd', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cjl', models.DecimalField(decimal_places=2, max_digits=13)),
                ('cje', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gupiao',
            unique_together=set([('code', 'name', 'date')]),
        ),
    ]
