# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yingyong1', '0004_auto_20190105_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gupiao',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
