# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-19 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yingyong1', '0011_auto_20190216_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gupiao',
            old_name='today_boll_center_line',
            new_name='bls',
        ),
        migrations.RenameField(
            model_name='gupiao',
            old_name='today_boll_down_line',
            new_name='blx',
        ),
        migrations.RenameField(
            model_name='gupiao',
            old_name='today_boll_up_line',
            new_name='blz',
        ),
    ]
